sudo: false
dist: trusty
language: node_js
node_js: 8.11
cache:
  directories:
    - node_modules
addons:
  firefox: latest
  chrome: stable
script:
  - yarn install --flat && if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" && "$TRAVIS_BRANCH" != quick/* ]]; then wct --module-resolution=node --npm --env saucelabs; else xvfb-run -s ''-screen 0 1024x768x24'' wct --npm; fi'
after_success:
  - 'cat ${TRAVIS_BUILD_DIR}/coverage/lcov.info | coveralls'

